name: Build

on:
    push: ~
    pull_request: ~
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday

jobs:
    tests:
        runs-on: ubuntu-latest
        name: "PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, Twig ${{ matrix.twig }}"
        strategy:
            fail-fast: false
            matrix:
                php: ["8.0", "8.1"]
                symfony: ["5.4.*", "6.0.*"]
                twig: ["^2.12", "^3.3"]

        steps:
            -
                uses: actions/checkout@v2

            -
                name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"
                    coverage: none

            -
                name: Restrict Symfony version
                if: matrix.symfony != ''
                run: |
                    composer global require --no-progress --no-scripts --no-plugins "symfony/flex:^1.10"
                    composer config extra.symfony.require "${{ matrix.symfony }}"
                    (cd src/Component && composer config extra.symfony.require "${{ matrix.symfony }}")

            -
                name: Restrict Twig version
                if: matrix.twig != ''
                run: |
                    composer require "twig/twig:${{ matrix.twig }}" --no-update --no-scripts

            -
                name: Remove Swiftmailer on Symfony >= 6
                if: ${{ true != contains( matrix.symfony, '5.4.*' ) }}
                run: |
                    composer remove --dev symfony/swiftmailer-bundle  --no-update --no-scripts
                    rm src/Bundle/spec/Sender/Adapter/SwiftMailerAdapterSpec.php

            -
                name: Install dependencies
                run: |
                    composer update ${{ matrix.composer-flags }} --no-scripts
                    (cd src/Component && composer update ${{ matrix.composer-flags }} --no-scripts)

            -
                name: Run analysis
                run: |
                    composer analyse
                    (cd src/Component && composer validate --strict)

            -
                name: Run component tests
                run: (cd src/Component && vendor/bin/phpspec run)

            -
                name: Run bundle tests
                run: composer test

            -
                name: Run lint container (with all services)
                run: |
                    rm -rf src/Bundle/test/var/cache
                    (cd src/Bundle/test && bin/console lint:container)

            -
                name: Run lint container (with Swift Mailer)
                if: ${{ true == contains( matrix.symfony, '5.4.*' ) }}
                run: |
                    rm -rf src/Bundle/test/var/cache
                    mv src/Bundle/test/config/packages/mailer.yaml mailer.yaml
                    composer remove symfony/mailer --dev
                    (cd src/Bundle/test && bin/console lint:container)

            -
                name: Run lint container (with symfony/mailer)
                run: |
                    rm -rf src/Bundle/test/var/cache
                    mv mailer.yaml src/Bundle/test/config/packages/mailer.yaml
                    mv src/Bundle/test/config/bundles.php src/Bundle/test/config/bundles_swift.php
                    mv src/Bundle/test/config/bundles_no_swift.php src/Bundle/test/config/bundles.php
                    composer remove symfony/swiftmailer-bundle --dev
                    composer require symfony/mailer --dev
                    (cd src/Bundle/test && bin/console lint:container)

            -
                name: Run lint container (with no mailers)
                run: |
                    rm -rf src/Bundle/test/var/cache
                    rm -f src/Bundle/test/config/packages/mailer.yaml
                    composer remove symfony/mailer --dev
                    (cd src/Bundle/test && bin/console lint:container)
